# Generated by Django 4.2.5 on 2023-09-18 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import thumbnails.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("images", "0002_alter_image_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Thumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to=thumbnails.models._upload_thumbnail_to_images
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="images.image",
                        verbose_name="image",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thumbnail",
                "verbose_name_plural": "Thumbnails",
            },
        ),
    ]
