# Generated by Django 4.2.5 on 2023-09-20 19:11

from django.db import migrations, models

import account_tiers.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "thumbnail_sizes",
                    models.JSONField(
                        default=list,
                        help_text="Comma-separated list of thumbnail sizes",
                        validators=[account_tiers.utils.validate_thumbnail_sizes],
                    ),
                ),
                (
                    "include_original_image_url",
                    models.BooleanField(
                        default=False,
                        help_text="Include a url to the originally uploaded file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Tier",
                "verbose_name_plural": "Account Tiers",
            },
        ),
    ]
