# Generated by Django 4.2.5 on 2023-09-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_tiers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttier",
            name="enabled_expiring_urls",
            field=models.BooleanField(
                default=False, help_text="Ability to create expiring image urls"
            ),
        ),
    ]
