# Generated by Django 4.2.5 on 2023-09-20 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_tiers", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_tier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="user",
                to="account_tiers.accounttier",
                verbose_name="account tier",
            ),
        ),
    ]
