# Generated by Django 4.2.5 on 2023-09-21 18:02

from django.db import migrations, models

import images.utils


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_alter_image_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="url_expiration_time",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The time that an additional url of the image expires in seconds",
                null=True,
                validators=[images.utils.validate_url_expiration_time],
            ),
        ),
    ]
